"""Simulate Railway's pre-workspace Postgres state and verify init_db() migrates cleanly.

This guards against the deployment regression where executescript() tried to
build idx_topics_workspace before _migrate_projects_to_workspaces had renamed
topics.project_id → topics.workspace_id.
"""
import os
import psycopg
import pytest


def _seed_legacy_schema(url: str) -> None:
    """Create a Postgres state that mirrors what existed BEFORE the workspace rewrite."""
    with psycopg.connect(url, autocommit=True) as conn:
        with conn.cursor() as cur:
            cur.execute("DROP SCHEMA IF EXISTS public CASCADE")
            cur.execute("CREATE SCHEMA public")
            cur.execute(
                """
                CREATE TABLE humans (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT,
                    github_login TEXT,
                    github_id BIGINT,
                    avatar_url TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE projects (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slug TEXT UNIQUE NOT NULL,
                    name TEXT NOT NULL,
                    description TEXT,
                    owner_human_id BIGINT REFERENCES humans(id),
                    repo_path TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE topics (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    slug TEXT UNIQUE NOT NULL,
                    title TEXT NOT NULL,
                    project_id BIGINT REFERENCES projects(id),
                    mode TEXT NOT NULL DEFAULT 'exploratory',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE agent_roles (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT UNIQUE NOT NULL,
                    description TEXT
                )
                """
            )
            cur.execute(
                """
                CREATE TABLE agent_instances (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    role_id BIGINT NOT NULL REFERENCES agent_roles(id),
                    human_id BIGINT NOT NULL REFERENCES humans(id),
                    device_label TEXT,
                    model TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """
            )
            # Seed realistic data: one human, one project they own, one topic.
            cur.execute(
                "INSERT INTO humans (name, email) VALUES ('alice', 'a@a') RETURNING id"
            )
            human_id = cur.fetchone()[0]
            cur.execute(
                "INSERT INTO projects (slug, name, owner_human_id) "
                "VALUES ('legacy', 'Legacy Project', %s) RETURNING id",
                (human_id,),
            )
            project_id = cur.fetchone()[0]
            cur.execute(
                "INSERT INTO topics (slug, title, project_id) VALUES ('t1', 'Topic 1', %s)",
                (project_id,),
            )


@pytest.fixture
def legacy_db(monkeypatch):
    """Postgres seeded with the pre-workspace schema, ready for init_db() migration."""
    url = os.environ.get(
        "LETS_TEST_DATABASE_URL",
        "postgresql://jacky@localhost:5432/lets_test",
    )
    _seed_legacy_schema(url)
    monkeypatch.setenv("DATABASE_URL", url)
    monkeypatch.delenv("LETS_DATABASE_URL", raising=False)
    from app import db as db_module
    db_module.reset_initialized_marker()
    return url


def test_init_db_migrates_legacy_schema(legacy_db):
    """init_db() must succeed and end up with topics.workspace_id populated."""
    from app.db import init_db, connect
    init_db()  # would raise UndefinedColumn before the migration order fix

    with connect() as conn:
        # topics.project_id is gone
        cols = conn.execute(
            "SELECT column_name FROM information_schema.columns "
            "WHERE table_name = 'topics' "
            "  AND column_name IN ('project_id', 'workspace_id')"
        ).fetchall()
        col_names = {r["column_name"] for r in cols}
        assert col_names == {"workspace_id"}

        # The legacy project rolled forward into workspaces with the same id
        ws = conn.execute(
            "SELECT id, slug, name FROM workspaces WHERE slug = 'legacy'"
        ).fetchone()
        assert ws is not None
        assert ws["name"] == "Legacy Project"

        # Topic is still referencing the same id, now via workspace_id
        topic = conn.execute(
            "SELECT slug, workspace_id FROM topics WHERE slug = 't1'"
        ).fetchone()
        assert topic["workspace_id"] == ws["id"]

        # Owner was promoted to workspace_members
        member = conn.execute(
            "SELECT role FROM workspace_members WHERE workspace_id = ?",
            (ws["id"],),
        ).fetchone()
        assert member["role"] == "owner"

        # Legacy projects table is gone
        rows = conn.execute(
            "SELECT table_name FROM information_schema.tables WHERE table_name = 'projects'"
        ).fetchall()
        assert rows == []
